# Generated by Django 2.0.6 on 2018-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porthole', '0002_auto_20180726_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifinetwork',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='porthole.VLAN'),
        ),
    ]
