# Generated by Django 2.0.6 on 2018-08-02 22:12

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    VLAN = apps.get_model('porthole', 'VLAN')
    WifiNetwork = apps.get_model('porthole', 'WifiNetwork')
    Organization = apps.get_model('porthole', 'Organization')
    for w in WifiNetwork.objects.all():
        if w.organization:
            org = w.organization
            org.wifi_network = w.ssid
            org.wifi_password = w.password
            org.vlan = w.vlan
            org.save()


class Migration(migrations.Migration):
    dependencies = [
        ('porthole', '0003_wifinetwork_vlan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlan',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='porthole.VLAN'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='dhcp_range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='dns',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='gateway',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vlan',
            name='netmask',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),

        # Port data up to Organization
        migrations.RunPython(forwards, migrations.RunPython.noop),

        # Remove WifiNetwork model
        migrations.RemoveField(
            model_name='wifinetwork',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='wifinetwork',
            name='vlan',
        ),
        migrations.DeleteModel(
            name='WifiNetwork',
        ),

    ]
